

source 'https://github.com/CocoaPods/Specs.git'

target 'BDLibrary', :exclusive => true do
    pod "BDLibrary", :path => "../"
end

target 'Tests', :exclusive => true do
    pod "BDLibrary", :path => "../"

  
end
